### ISSUE TITLE
Querys can have conditions via GET param

### ISSUE THREAD

**Issue by placer14** [filecoin-project/slate-sentinel#1]
In order to better manage queries to the API, a where or filter GET param to requests would allow conditions to be applied to a query. Would LOVE the full flexibility of SQL conditions... but realistically I'd be okay with we limit the conditions to parsed strings. Here are the condition operators we care most about `=` , `!=`, `<`, `<=`, `>` , `>=` , `AND`, `OR`, `()` . _NOTE: This represents a security risk for SQL injection, care must be taken to ensure the database source is not exposed to this variety of attack._

Param names for consideration: `where`, `filter`
Format for condition inputs are a detail left for implementation.

**Comment by jimmylee** [comment]
Sorry for missing this PR https://github.com/filecoin-project/slate-sentinel/pull/2

Will merge once they make a small change

**Comment by jimmylee** [comment]
Resolved in PR, thanks @placer14 and sorry this took so long.
